import Head from "next/head";
import React, { useEffect, useState } from "react";
import { useSelector, useDispatch } from "react-redux";
import {
  fetchAddUser,
  fetchDeleteUser,
  fetchUsers,
} from "../redux/users/usersActions";
import { TrashIcon, PencilIcon } from "@heroicons/react/solid";
import Popup from "../components/Popup";
import { fetchSingleUser } from "../redux/user/userActions";
import axios from "axios";
import Pagination from "../components/Pagination";
import Image from "next/image";
import { getRandomImg } from "../helpers/imagePicker";
import Link from "next/link";
import Navbar from "../components/Navbar";
import { getSession, signIn, useSession } from "next-auth/client";

export default function Home() {
  const [session, loadingAuth] = useSession();
  console.log({ session, loadingAuth });
  const users = useSelector((state) => state.users.users);
  const dispatch = useDispatch();
  const [showModal, setShowModal] = useState(false);

  const [showInput, setShowInput] = useState(false);
  const [name, setName] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const [usersPerPage, setUsersPerPage] = useState(5);
  const [pages, setPages] = useState();
  const [loading, setLoading] = useState(true);

  const indexOfLastUser = currentPage * usersPerPage;
  const indexOfFirstUser = indexOfLastUser - usersPerPage;
  const currentUsers = users.slice(indexOfFirstUser, indexOfLastUser);

  useEffect(() => {
    dispatch(fetchUsers());
  }, []);

  const onUserClick = (user) => {
    setShowModal(true);
    dispatch(fetchSingleUser(user));
  };

  const onAddUserClick = () => {
    setShowInput((input) => !input);
  };

  const addUser = () => {
    if (users) {
      const Ids = users.map((user) => user.id);
      const IdsSorted = Ids.sort((a, b) => a - b);
      dispatch(
        fetchAddUser({
          name: name,
          id: IdsSorted[IdsSorted.length - 1] + 1,
          image: getRandomImg(),
        })
      );
    }

    setName("");
  };

  const paginate = (pageNumber) => {
    setCurrentPage(pageNumber);
  };

  if (!session) {
    return (
      <div className="flex flex-col items-center">
        <h2 className="text-center font-bold mt-5">
          Please Sign in to continue...
        </h2>
        <Link href="/api/auth/signin">
          <a
            className="text-white hover:text-blue-800 mr-4 bg-blue-500 px-5 py-3 rounded-md"
            onClick={(e) => {
              e.preventDefault();
              signIn("");
            }}
          >
            Sign In
          </a>
        </Link>
      </div>
    );
  }

  return (
    <div>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar name={session && session.user.name} />
      <div className="flex flex-col items-center justify-center mt-5">
        <div className="flex">
          <input
            type="number"
            placeholder="users per page"
            min={1}
            onChange={(e) => setPages(e.target.value)}
            value={pages}
            className="shadow border m-2 flex-grow text-gray appearance-none rounded border-gray-200 focus:border-purple-500 focus:bg-white outline-none"
          />
          <button
            onClick={() => setUsersPerPage(pages)}
            className="bg-blue-200 py-2 px-3 rounded-xl font-semibold text-red-800"
          >
            Set
          </button>
        </div>

        <table className="table-auto bg-red-200 ">
          <thead>
            <tr className="border-2">
              <th className="text-3xl">Users</th>
            </tr>
          </thead>
          <tbody className="bg-white ">
            {users &&
              currentUsers.map((user) => (
                <tr
                  key={user.id}
                  className="bg-emerald-200 border-2 border-gray-300 hover:bg-indigo-200 hover:scale-105"
                >
                  <td className="font-semibold text-2xl px-6 py-4 whitespace-nowrap ">
                    <Link href={`/${user.id}`}>
                      <div className="flex items-center cursor-pointer">
                        <Image
                          src={user.image}
                          width={60}
                          height={60}
                          className="rounded-lg "
                        />
                        <p className="font-semibold ml-2">{user.name}</p>
                      </div>
                    </Link>
                  </td>
                  <td>
                    <PencilIcon
                      className="h-7 w-7 text-blue-500 cursor-pointer ml-2"
                      onClick={() => onUserClick(user)}
                    />
                  </td>
                  <td>
                    <TrashIcon
                      className="h-7 w-7 text-red-500 cursor-pointer mr-2"
                      onClick={() => dispatch(fetchDeleteUser(user))}
                    />
                  </td>
                </tr>
              ))}
          </tbody>
        </table>
        <button
          className="mt-2 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
          onClick={onAddUserClick}
        >
          {!showInput ? "Add user" : "Close"}
        </button>
        {showInput && (
          <div className="flex items-center justify-center">
            <input
              type="text"
              placeholder="Enter name"
              onChange={(e) => setName(e.target.value)}
              value={name}
              className="mt-2 flex-grow bg-gray-200 appearance-none border-2 border-gray-200 rounded w-1/3 py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
            />
            <button
              className="ml-2 bg-gray-300 font-bold py-1 px-2 rounded-md"
              onClick={addUser}
            >
              Add
            </button>
          </div>
        )}
      </div>
      <Pagination
        totalUsers={users.length}
        usersPerPage={usersPerPage}
        paginate={paginate}
      />
      <Popup showModal={showModal} setShowModal={setShowModal} />
    </div>
  );
}
